config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
 
  get 'pages/home'
 
  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks"
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  root to: "students#index"
  resources :students  
  #resource :search
  get '/search' => 'search#search_students'
  resources :messages

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="container">
  <div style="margin-top :10px;">
    <% flash.each do |key, value| %>
      
      <div>
          <%= value %>
      </div>
    <% end %>    
  </div>

  <div class="header_container">
    <% if current_user %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
      <%= link_to "New Student", new_student_path, class: "btn btn-primary" %>
      <%= link_to "Student List", root_path, class: "btn btn-primary" %>
      <%= link_to "LIVE Messages", messages_path, class: "btn btn-primary" %>
     
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "btn btn-info" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info" %>
    <% end %>
  </div>
</div>

  

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "btn btn-info" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "layouts/header" %>
    <%= yield %>
   
  </body>
</html>